# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=63, unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('startups', models.ManyToManyField(to='organizer.Startup')),
                ('tag', models.ManyToManyField(related_name='blog_posts', to='organizer.Tag')),
            ],
        ),
    ]
